config/routes.rb
Collect::Engine.routes.draw do

  resources :forms

  ## Routes to send forms from the Rails app to the ODK Collect mobile app
  get 'formList', to: 'odk#index', as: :odk, defaults: { format: 'xml' }
  resources :odk, defaults: { format: 'xml' }, only: [:index, :show]

  ## Route to submit forms from the ODK Collect mobile app to the Rails app.
  match '/submission', to: 'odk#submission', via: :all, defaults: { format: 'xml' }
  
end

app/models/collect/application_record.rb
module Collect
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/collect/form.rb
module Collect
  class Form < ApplicationRecord

    ## TO DO: add a callback that saves the updated_at in an array to populate xml forms w/ versions with:
    ## listAllVersions 
    ## see: https://docs.getodk.org/openrosa-form-list/

    ## Each form has: name, description, and .xml document attached with Active Storage
    ## The document must be a .xml file, because ODK Collect only works with xml.
    ## You must create an XLS form using an Excel spreadsheet according to this documentation:
    ## https://xlsform.org/en/
    ## Then convert the XLS form into an xml document with this converter:
    ## https://getodk.org/xlsform/
    ## Once you have a form prepared in the xml format, then upload it here:
    ## http://localhost:3000/collect/forms/new

    validates :name, presence: true, uniqueness: true
    validates :description, presence: true

    has_one_attached :document, dependent: :destroy

    validate :correct_document_mime_type

    private

      def correct_document_mime_type
        if !document.attached? || !document.content_type.in?(%w(application/xml))
          errors.add(:document, 'invalid! The file must be an XML file.')
        end
      end

  end
end

app/controllers/collect/application_controller.rb
require_dependency "collect/application_controller"

module Collect
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

  end
end

app/controllers/collect/forms_controller.rb
module Collect
  class FormsController < ApplicationController
    include Collect::BaseFormsControllerActions

  end
end

app/controllers/collect/odk_controller.rb
module Collect
  class OdkController < ApplicationController
    ## Resource for use ActiveSupport Concerns in order to make overwritable methods for ODK
    ## Source
    ## http://stackoverflow.com/questions/7719633/how-to-extend-rails-engines-controllers-properly
    ## http://edgeguides.rubyonrails.org/engines.html#overriding-models-and-controllers
    ##
    ##
    ## Github Gist: https://gist.github.com/trejo08/11df06b3c6ff8fa26c610447005b721f
    include Collect::BaseOdkControllerActions

  end
end

app/controllers/concerns/collect/base_forms_controller_actions.rb
module Collect
  module BaseFormsControllerActions
    extend ActiveSupport::Concern

    ## This controller lets you manage forms.
    ## Forms can be download in the ODK Collect mobile app.
    #
    ## A Form has:
    ## name
    ## description
    ## document (attached with active storage).
    #
    ## The document must be type xml because:
    ## ODK Collect uses the xml document to display the Form in the ODK Collect mobile app.
    #
    ## Step 1: Create an XLS form using an Excel spreadsheet according to this documentation:
    ## Use the example in:
    ## /test/fixtures/files/tree_survey.xlsx
    ## See xlsform docs:
    ## https://xlsform.org/en/
    #
    ## Step: 2. Convert the XLS form into an xml document with this converter:
    ## https://getodk.org/xlsform/
    ## If you use the tree_survey.xlsx file from step 2 your output is a file like this:
    ## /test/fixtures/files/tree_survey.xml
    #
    ## Step 3: Go to:
    ## http://localhost:3000/collect/forms/
    #
    ## Step 4: Click "New Form"
    ## http://localhost:3000/collect/forms/new
    #
    ## Step 5: Save the name, description, and upload the form xml document:
    ## The file from: /test/fixtures/files/tree_survey.xml

    def index
      @forms = Form.order(created_at: :desc)        
    end

    def show
      @form = Form.find(params[:id])
    end

    def new
      @form = Form.new
    end

    def create
      @form = Form.new(form_params)
      if @form.save
        flash[:notice] = "Form was saved."
        redirect_to form_path(@form)
      else
        flash[:notice] = "Form could not be saved."
        render 'new'
      end
    end

    def edit
      @form = Form.find(params[:id])
    end

    def update
      @form = Form.find(params[:id])
      if @form.update(form_params)
        flash[:notice] = "Form was updated."
        redirect_to form_path(@form)
      else
        flash[:notice] = "Form could not be updated."
        render 'edit'
      end
    end

    def destroy
      @form = Form.find(params[:id])
      @form.destroy
      if @form.destroy      
        flash[:notice] = "Form was destroyed."
        redirect_to forms_path
      else
        flash[:notice] = "Form could not be destroyed."
        redirect_to form_path(@form)
      end
    end

    private

      def form_params
        params.require(:form).permit(
          :name,
          :description,
          :document
        )
      end

  end
end

app/controllers/concerns/collect/base_odk_controller_actions.rb
module Collect
  module BaseOdkControllerActions
    extend ActiveSupport::Concern

    def self.included(base)
      base.before_action :set_header, only: %i[index submission]
      base.respond_to :xml
    end

    ## The index action lets ODK Collect get a list of forms from your app
    ## See this line in config/routes: get 'formList', to: 'odk#index', as: :odk, defaults: { format: 'xml' }
    ## It works like this:
    ## When a user selects "Get forms" in ODK Collect, ODK Collect sends a get request to this action
    ## Each form in the list of foms has a <downloadUrl/> tag 
    ## This tag lets ODK Collect know to look for the xml document in the show action below when the user clicks "Download blank forms" in ODK Collect
    #
    ## To see the xml layout of each form see:
    ## views/collect/odk/index.xml.erb 
    def index
      @forms = Collect::Form.all
      respond_to do |format|
        format.xml { render 'index.xml' }
      end
    end

    ## The show action lets ODK Collect download the xml form from your server
    ## It works like this:
    ## Each xml form in the list of forms from the index action has a <downloadUrl/> tag
    ## The downloadUrl tag makes ODK Collect send a get request to this action.
    ## This action sends form's xml document to ODK Collect.
    ## See the ODK Collec docs here for more info: https://docs.getodk.org/openrosa-form-list/
    def show
      doc = Collect::Form.find(params[:id])
      send_data doc.document.download, filename: doc.document.filename.to_s, content_type: doc.document.content_type
    end

    def submission
      ## This submissions method is replaced by the 'submission' method in: 
      ## lib/generators/collect/templates/odk_controller.rb

      if request.method.eql?('POST')
        ## put your logic code here like the below example
        # hash = Crack::XML.parse(File.read(params[:xml_submission_file].path))
        # model = set_model(hash)
        model = 'nothing_device'
        if model != 'device_id'
        #   object = prepare_object(model, hash)
        #   form = "Demo::#{model.singularize.camelize}".constantize.new(object)
        #   respond_to do |format|
        #     if form.save
        #       format.xml { render status: 201 }
        #     else
        #       format.xml { render status: form.errors.messages }
        #     end
        #   end
        else
          render status: 201
        end
      else
        render status: 204
      end
    end

    private

      def set_header
        response.headers['X-OpenRosa-Version'] = '1'
        response.headers['Content-Type'] = 'text/xml; charset=utf-8'
      end

  end
end

app/helpers/collect/application_helper.rb
module Collect
  module ApplicationHelper
  end
end

app/helpers/collect/forms_helper.rb
module Collect
  module FormsHelper
  end
end

app/helpers/collect/odk_helper.rb
module Collect
  module OdkHelper
  end
end

app/views/collect/forms/_form.html.erb
<%= form_for @form do |f| %>  

  <% if @form.errors.any? %>
    <h4>Errors in the form!</h4>
    <ul style="padding-bottom: 20px;">
      <% @form.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>  
    </ul>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description, required: true %>
  </p>
  <p>
    <%= f.label :document %>
    <%= f.file_field :document %>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/collect/forms/edit.html.erb
<h1><%= link_to "Forms", forms_path %> / <%= link_to @form.name, form_path(@form) %> / Edit</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>XML Form</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @form.name %></td>
      <td>
        <% if @form.document.attached? %>
          <%= @form.document.filename %>
        <% else %>
          No File Attached
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<%= render 'form', form: @form %>

app/views/collect/forms/index.html.erb
<h1>Forms</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desciption</th>
      <th>XML Form</th>
      <%#<th colspan="3">Actions</th>%>
    </tr>
  </thead>
  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= link_to form.name, form_path(form) %></td>
        <td><%= form.description %></td>
        <td>
          <% if form.document.attached? %>
            <%= form.document.filename %>
          <% else %>
            No File Attached
          <% end %>
        </td>
        <%#<td><%= link_to "Show", form_path(form) %></td>
        <%#<td><%= link_to "Edit", edit_form_path(form) %></td>
        <%#<td><%= link_to "Destroy", form_path(form), method: :delete, data: { confirm: "Are you sure you want to delete this form?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Form', new_form_path %>

app/views/collect/forms/new.html.erb
<h1><%= link_to "Forms", forms_path %> / New Form</h1>
<%= render 'form', form: @form %>
<%= link_to 'Back', forms_path %>

app/views/collect/forms/show.html.erb
<h1><%= link_to "Forms", forms_path %> / <%= @form.name %></h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desciption</th>
      <th>XML Form</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @form.name %></td>
      <td><%= @form.description %></td>
      <td>
        <% if @form.document.attached? %>
          <%= @form.document.filename %>
        <% else %>
          No File Attached
        <% end %>
      </td>
      <td><%= link_to "Edit", edit_form_path(@form) %></td>
      <td><%= link_to "Destroy", form_path(@form), method: :delete, data: { confirm: "Are you sure you want to delete this form?" } %></td>
    </tr>
  </tbody>
</table>

app/views/collect/odk/index.xml.erb
<%# See ODk Collect documentation for more info on improving this: https://docs.getodk.org/openrosa-form-list/ %>
<?xml version='1.0' encoding='UTF-8' ?>
<xforms xmlns="http://openrosa.org/xforms/xformsList">
  <% @forms.each do |file| %>
  <xform>
    <formID><%= file.id %></formID>
    <name><%= file.name %></name>
    <version><%= file.updated_at.to_i %></version>
    <hash>md5:c28fc778a9291672badee04ac880a05d</hash>
    <descriptionText><%= file.description %></descriptionText>
    <downloadUrl><%= ENV['DOMAIN'] %>/collect/odk/<%= file.id %></downloadUrl>
  </xform>
  <% end %>
</xforms>

app/views/layouts/collect/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collect</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%# This throws an error in the collect views
  <%#= stylesheet_link_tag "collect/application", media: "all" %>
  <style>
    table{
      border-collapse: collapse;
    }
    td{
      border: 1px solid #000;
      padding: 10px;
    }
  </style>
</head>
<body>

  <div style="padding: 40px 0 0 60px;">
    <h4 id="notice"><%= notice %></h4>
    <%= yield %>
  </div>

</body>
</html>